//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CookingAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecipeIngredient
    {
        public int recipeIngredientId { get; set; }
        public int recipeId { get; set; }
        public int measurementId { get; set; }
        public int ingredientId { get; set; }
        public double measurementQuantity { get; set; }
    
        public virtual Ingredient Ingredient { get; set; }
        public virtual MeasurementUnit MeasurementUnit { get; set; }
        public virtual Recipe Recipe { get; set; }
    }
}
